name: Symfony

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

permissions:
  contents: read

jobs:
  setup-env:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name : Echo github
        env : { CONTENT : "${{ toJson(github) }}" }
        run : "echo $CONTENT"
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          extensions: imagick gd bcmath intl zip
          coverage: xdebug
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create Database
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --env=test
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=tests-report.xml
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' coverage.xml
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' tests-report.xml

